spring.application.name=ms-security
#server.port=8081

spring.mongodb.uri=mongodb+srv://luisaibarra38302_db_user:lfit123456@clusters.mmupefj.mongodb.net/?appName=Clusters
spring.mongodb.database=db_security
jwt.secret=aaa
jwt.expiration=3600000