spring.application.name=ms-security
#server.port=8081

spring.mongodb.uri=mongodb+srv://luisaibarra38302_db_user:lfit123456@clusters.mmupefj.mongodb.net/?appName=Clusters
spring.mongodb.database=db_security
jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUX0hTNTEyX0xGSVRfMjAyNl9TZWN1cmVfS2V5X0Jhc2U2NA==
jwt.expiration=3600000