spring.application.name=ms-security

spring.mongodb.uri=mongodb+srv://luisaibarra38302_db_user:lfit123456@clusters.mmupefj.mongodb.net/?appName=Clusters
spring.mongodb.database=db_security

jwt.secret=aaa
jwt.expiration=3600000

github.client-id=Ov23liwKD4psTExQ0UFy
github.client-secret=bae91c21c4c9ed6f639e542fdc18e6bfdad69556
github.frontend-url=http://localhost:4200



google.client-id=281342679229-to99llpf18nldcuar94bouv25908iqb1.apps.googleusercontent.com
google.client-secret=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
google.frontend-url=http://localhost:4200

microsoft.client-id=pending
microsoft.client-secret=pending
microsoft.tenant-id=pending
microsoft.frontend-url=http://localhost:4200